syntax = "proto3";
package stellar.v1;

import "google/protobuf/empty.proto";
import "proto/stellar/v1/common.proto";

service DocumentService {
  rpc Get(GetDocumentRequest) returns (Document);
  rpc Create(CreateDocumentRequest) returns (Document);
  rpc Update(UpdateDocumentRequest) returns (Document);
  rpc Delete(DeleteDocumentRequest) returns (google.protobuf.Empty);
  rpc List(ListDocumentsRequest) returns (stream DocumentListItem);
}

message GetDocumentRequest {
  string collection = 1;
  string key = 2;
}

message CreateDocumentRequest {
  string collection = 1;
  map<string, Value> fields = 2;
}

message UpdateDocumentRequest {
  string collection = 1;
  string key = 2;
  map<string, Value> fields = 3;
}

message DeleteDocumentRequest {
  string collection = 1;
  string key = 2;
}

message ListDocumentsRequest {
  string collection = 1;
  PaginationRequest pagination = 2;
}

message DocumentListItem {
  oneof payload {
    Document document = 1;
    bool has_more = 2;
  }
}
