mod cli;

use clap::Parser;
use cli::args::{Cli, Commands, SchemaAction};

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    let cli = Cli::parse();

    match cli.command {
        Commands::Serve {
            port,
            grpc_port,
            login_body_limit,
            http_body_limit,
            grpc_max_message_size,
            grpc_concurrency_limit,
            grpc_max_concurrent_streams,
            host,
            insecure_allow_remote,
            tls_cert_file,
            tls_key_file,
            non_browser_api,
            data,
            verbose,
            quiet,
            query_timeout,
            jwt_secret,
            jwt_secret_file,
            jwt_ttl,
            max_db_concurrency,
            db_deadline,
            index_build_chunk_size,
            index_build_memory_budget,
            index_build_workers,
            max_login_concurrency,
            login_rate_per_second,
            login_burst,
            login_client_rate_per_second,
            login_client_burst,
            max_login_clients,
            login_client_retention,
            query_client_rate_per_second,
            query_client_burst,
            max_query_clients,
            query_client_retention,
            trusted_proxy_hops,
            metrics_max_query_stats,
            metrics_query_retention_days,
            metrics_max_index_stats,
            metrics_index_retention_days,
            metrics_max_collection_stats,
            metrics_collection_retention_days,
        } => {
            cli::commands::serve::run(
                port,
                grpc_port,
                login_body_limit,
                http_body_limit,
                grpc_max_message_size,
                grpc_concurrency_limit,
                grpc_max_concurrent_streams,
                host,
                insecure_allow_remote,
                tls_cert_file,
                tls_key_file,
                non_browser_api,
                std::env::var("STELLARDB_CORS_ALLOW_ORIGINS").ok(),
                data,
                verbose,
                quiet,
                query_timeout,
                jwt_secret,
                jwt_secret_file,
                jwt_ttl,
                max_db_concurrency,
                db_deadline,
                index_build_chunk_size,
                index_build_memory_budget,
                index_build_workers,
                max_login_concurrency,
                login_rate_per_second,
                login_burst,
                login_client_rate_per_second,
                login_client_burst,
                max_login_clients,
                login_client_retention,
                query_client_rate_per_second,
                query_client_burst,
                max_query_clients,
                query_client_retention,
                trusted_proxy_hops,
                metrics_max_query_stats,
                metrics_query_retention_days,
                metrics_max_index_stats,
                metrics_index_retention_days,
                metrics_max_collection_stats,
                metrics_collection_retention_days,
            )
            .await
        }
        Commands::Sql {
            query,
            host,
            database,
            json,
            pretty,
        } => cli::commands::sql::run(query, host, database, json, pretty).await,
        Commands::Schema { action } => match action {
            SchemaAction::Show {
                collection,
                host,
                database,
                json,
            } => cli::commands::schema::show::run(collection, host, database, json).await,
            SchemaAction::List {
                host,
                database,
                json,
            } => cli::commands::schema::list::run(host, database, json).await,
            SchemaAction::Apply {
                path,
                host,
                database,
                dry_run,
            } => cli::commands::schema::apply::run(path, host, database, dry_run).await,
            SchemaAction::Export {
                path,
                host,
                database,
            } => cli::commands::schema::export::run(path, host, database).await,
        },
        Commands::Backup { data, output } => cli::commands::backup::backup(data, output),
        Commands::Restore { input, data } => cli::commands::backup::restore(input, data),
    }
}
